server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenpo_db
    username: tenpo_user
    password: tenpo_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: INFO
